// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIV6Zi5Eu_3xQjT58FJUcnz4Pu8rT5Wek',
    appId: '1:130835918757:android:cf79ff9e0667f39115824c',
    messagingSenderId: '130835918757',
    projectId: 'sportmate-2478e',
    storageBucket: 'sportmate-2478e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYjMUErl9rUeIRYktNAXwLtBHxrSIRO1A',
    appId: '1:130835918757:ios:20ffcb3b0189f57415824c',
    messagingSenderId: '130835918757',
    projectId: 'sportmate-2478e',
    storageBucket: 'sportmate-2478e.appspot.com',
    androidClientId: '130835918757-392sd24coqqcrbhi4cnmf1alebrtrqnq.apps.googleusercontent.com',
    iosClientId: '130835918757-b90fm2vvjrmsg54bfmtmjqqcuo3m61hj.apps.googleusercontent.com',
    iosBundleId: 'com.sportmate.sportmate',
  );
}
